import type { CSSProperties } from "react";
import { fontFamily, monoFamily } from "./fonts";

export const globalStyles: Record<string, CSSProperties> = {
  page: {
    alignItems: "flex-start",
    display: "flex",
    fontFamily,
    minHeight: "100vh",
    overflow: "auto",
    padding: 0,
    position: "relative",
    transition: "background 0.2s ease, color 0.2s ease",
  },
  navbar: {
    alignItems: "center",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    boxSizing: "border-box",
    display: "flex",
    height: "56px",
    justifyContent: "space-between",
    left: 0,
    padding: "0 clamp(16px, 5vw, 40px)",
    position: "fixed",
    right: 0,
    top: 0,
    width: "100%",
    zIndex: 2,
  },
  brand: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
  },
  brandText: {
    fontFamily,
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: 1.2,
  },
  installButton: {
    alignItems: "center",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "999px",
    color: "#e4e1ee",
    cursor: "not-allowed",
    display: "inline-flex",
    fontFamily,
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    lineHeight: 1.3,
    padding: "6px 14px",
    transition: "background 0.2s ease, border-color 0.2s ease",
  },
  loaderContainer: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    height: "100vh",
    width: "100%",
    position: "relative",
    zIndex: 1,
  },
  loaderIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dotCanvas: {
    height: "100%",
    left: 0,
    pointerEvents: "none",
    position: "fixed",
    top: 0,
    width: "100%",
    zIndex: 0,
  },
  spin: {
    animation: "spin 1s linear infinite",
  },
  content: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "0 clamp(16px, 3vw, 40px)",
    boxSizing: "border-box",
  },
  repoHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: "20px",
    paddingTop: "clamp(70px, 15vh, 80px)",
    paddingBottom: "clamp(20px, 5vh, 32px)",
  },
  chipRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  chip: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: "999px",
    fontFamily: monoFamily,
    fontSize: "12px",
    padding: "6px 14px",
    lineHeight: 1.5,
    display: "inline-flex",
    alignItems: "center",
  },
  dashboardGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "0",
  },
  statLabelSmall: {
    fontFamily,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: 1.4,
  },
};

export function getGlassSurface(): CSSProperties {
  return {
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.08)",
    backdropFilter: "blur(12px)",
    borderRadius: "16px",
    padding: "24px",
  };
}
